import { z } from "zod";

const envSchema = z.object({
  DATABASE_URL: z.string().min(1),
  POINTER_APP_URL: z.string().url().default("http://localhost:3000"),
  POINTER_ROOT_DOMAIN: z.string().default("localhost:3000"),
  POINTER_SESSION_SECRET: z.string().min(32).default("pointer-local-development-secret-change-me-123"),
  POINTER_STORAGE_DRIVER: z.enum(["local", "supabase", "cloudinary"]).default("local"),
  POINTER_STORAGE_LOCAL_DIR: z.string().default("public/uploads"),
  POINTER_SUPABASE_URL: z.string().optional(),
  POINTER_SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
  POINTER_SUPABASE_BUCKET: z.string().default("pointer-photos"),
  POINTER_CLOUDINARY_CLOUD_NAME: z.string().optional(),
  POINTER_CLOUDINARY_API_KEY: z.string().optional(),
  POINTER_CLOUDINARY_API_SECRET: z.string().optional(),
  POINTER_CLOUDINARY_FOLDER: z.string().default("pointer/time-records"),
  POINTER_MAPBOX_ACCESS_TOKEN: z.string().optional(),
  POINTER_WEB_PUSH_SUBJECT: z.string().default("mailto:no-reply@pointer.local"),
  POINTER_WEB_PUSH_PUBLIC_KEY: z.string().optional(),
  POINTER_WEB_PUSH_PRIVATE_KEY: z.string().optional(),
  POINTER_GEOCODING_PROVIDER: z.enum(["none", "nominatim"]).default("nominatim"),
  POINTER_GEOCODING_USER_AGENT: z.string().default("Pointer/0.1 (isolated-mvp)"),
  POINTER_EMAIL_FROM: z.string().default("Pointer <no-reply@pointer.local>"),
  POINTER_SMTP_HOST: z.string().optional(),
  POINTER_SMTP_PORT: z.coerce.number().int().positive().default(587),
  POINTER_SMTP_SECURE: z
    .union([z.boolean(), z.string()])
    .transform((value) => value === true || value === "true")
    .default(false),
  POINTER_SMTP_USER: z.string().optional(),
  POINTER_SMTP_PASSWORD: z.string().optional(),
  POINTER_CRON_SECRET: z.string().min(16).default("pointer-cron-secret-exclusivo"),
  CRON_SECRET: z.string().optional(),
  POINTER_STRIPE_SECRET_KEY: z.string().optional(),
  POINTER_STRIPE_WEBHOOK_SECRET: z.string().optional(),
  POINTER_STRIPE_PORTAL_CONFIG_ID: z.string().optional(),
  POINTER_STRIPE_PRICE_STARTER: z.string().optional(),
  POINTER_STRIPE_PRICE_PRO: z.string().optional(),
  POINTER_STRIPE_PRICE_ENTERPRISE: z.string().optional(),
  POINTER_BILLING_GRACE_DAYS: z.coerce.number().int().min(0).default(5),
});

export const env = envSchema.parse({
  DATABASE_URL: process.env.DATABASE_URL,
  POINTER_APP_URL: process.env.POINTER_APP_URL,
  POINTER_ROOT_DOMAIN: process.env.POINTER_ROOT_DOMAIN,
  POINTER_SESSION_SECRET: process.env.POINTER_SESSION_SECRET,
  POINTER_STORAGE_DRIVER: process.env.POINTER_STORAGE_DRIVER,
  POINTER_STORAGE_LOCAL_DIR: process.env.POINTER_STORAGE_LOCAL_DIR,
  POINTER_SUPABASE_URL: process.env.POINTER_SUPABASE_URL,
  POINTER_SUPABASE_SERVICE_ROLE_KEY: process.env.POINTER_SUPABASE_SERVICE_ROLE_KEY,
  POINTER_SUPABASE_BUCKET: process.env.POINTER_SUPABASE_BUCKET,
  POINTER_CLOUDINARY_CLOUD_NAME: process.env.POINTER_CLOUDINARY_CLOUD_NAME,
  POINTER_CLOUDINARY_API_KEY: process.env.POINTER_CLOUDINARY_API_KEY,
  POINTER_CLOUDINARY_API_SECRET: process.env.POINTER_CLOUDINARY_API_SECRET,
  POINTER_CLOUDINARY_FOLDER: process.env.POINTER_CLOUDINARY_FOLDER,
  POINTER_MAPBOX_ACCESS_TOKEN: process.env.POINTER_MAPBOX_ACCESS_TOKEN,
  POINTER_WEB_PUSH_SUBJECT: process.env.POINTER_WEB_PUSH_SUBJECT,
  POINTER_WEB_PUSH_PUBLIC_KEY: process.env.POINTER_WEB_PUSH_PUBLIC_KEY,
  POINTER_WEB_PUSH_PRIVATE_KEY: process.env.POINTER_WEB_PUSH_PRIVATE_KEY,
  POINTER_GEOCODING_PROVIDER: process.env.POINTER_GEOCODING_PROVIDER,
  POINTER_GEOCODING_USER_AGENT: process.env.POINTER_GEOCODING_USER_AGENT,
  POINTER_EMAIL_FROM: process.env.POINTER_EMAIL_FROM,
  POINTER_SMTP_HOST: process.env.POINTER_SMTP_HOST,
  POINTER_SMTP_PORT: process.env.POINTER_SMTP_PORT,
  POINTER_SMTP_SECURE: process.env.POINTER_SMTP_SECURE,
  POINTER_SMTP_USER: process.env.POINTER_SMTP_USER,
  POINTER_SMTP_PASSWORD: process.env.POINTER_SMTP_PASSWORD,
  POINTER_CRON_SECRET: process.env.POINTER_CRON_SECRET,
  CRON_SECRET: process.env.CRON_SECRET,
  POINTER_STRIPE_SECRET_KEY: process.env.POINTER_STRIPE_SECRET_KEY,
  POINTER_STRIPE_WEBHOOK_SECRET: process.env.POINTER_STRIPE_WEBHOOK_SECRET,
  POINTER_STRIPE_PORTAL_CONFIG_ID: process.env.POINTER_STRIPE_PORTAL_CONFIG_ID,
  POINTER_STRIPE_PRICE_STARTER: process.env.POINTER_STRIPE_PRICE_STARTER,
  POINTER_STRIPE_PRICE_PRO: process.env.POINTER_STRIPE_PRICE_PRO,
  POINTER_STRIPE_PRICE_ENTERPRISE: process.env.POINTER_STRIPE_PRICE_ENTERPRISE,
  POINTER_BILLING_GRACE_DAYS: process.env.POINTER_BILLING_GRACE_DAYS,
});
